# version format
version: 0.1.{build}-{branch}

branches:
  except:
    - gh_pages

skip_tags: true

clone_depth: 1

os: Windows Server 2012 R2

before_build:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14" -DBOOST_ROOT=C:\Libraries\boost_1_59_0 -DCDM_BOOST_ROOT_FOR_TESTING=C:\Libraries\boost_1_59_0 -DCDM_TESTS_RUNNING_ON_APPVEYOR=ON ..

build_script:
  - cmake --build . --config Release

after_build:

before_test:

test_script:
  - cd system_test
  - Release\system_test.exe --report_level=detailed --log_level=all

after_test:

on_success:
on_failure:
on_finish:
